host: migsharedutilitiesservice.perseusedge.com
namespace: migration
secretname: sharedutilities-migration-secret-appsettings
secretProviderClass: aks-secret-nf-migration
secretSPName: perseus-secret-sp-migration
aspnetcore: Migration
#sharedutilitiesrepo: PerseusNonProdACR.azurecr.io/sharedutilities_qa:latest
replicas: 1
sslcert: perseusedgesslcert
limitcpu: 500m
limitmemory: 800Mi
requestscpu: 300m
requestsmemory: 500Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70