host: migsharedutilitiesservice.perseusedge.com
namespace: migration
#secretname: sharedutilities-prod-secret-appsettings
aspnetcore: Migration
#sharedutilitiesrepo: PerseusNonProdACR.azurecr.io/sharedutilities_qa:latest
replicas: 1
sslcert: perseusedgesslcert
limitcpu: 8m
limitmemory: 400Mi
requestscpu: 5m
requestsmemory: 300Mi
autoscaling:
  enabled: false