host: sharedutilitiesservice.login.schoolcafe.com
name: sharedutilities
namespace: prod
secretname: sharedutilities-prod-secret-appsettings
aspnetcore: Production
#sharedutilitiesrepo: PerseusNonProdACR.azurecr.io/sharedutilities_qa:latest
replicas: 2
sslcert: loginschoolcafesslcert
limitcpu: 500m
limitmemory: 800Mi
requestscpu: 400m
requestsmemory: 600Mi