host: sharedutilitiesservice.login.schoolcafe.com
name: sharedutilities
namespace: prod
secretname: sharedutilities-prod-secret-appsettings
aspnetcore: Production
secretProviderClass: aks-secret-nf-prod
secretSPName: perseus-secret-sp-prod
#sharedutilitiesrepo: PerseusNonProdACR.azurecr.io/sharedutilities_qa:latest
replicas: 2
sslcert: loginschoolcafesslcert
limitcpu: 500m
limitmemory: 800Mi
requestscpu: 300m
requestsmemory: 500Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70