host: stgsharedutilitiesservice.perseusedge.com
namespace: staging
secretname: sharedutilities-stg-secret-appsettings
aspnetcore: Staging
#sharedutilitiesrepo: PerseusNonProdACR.azurecr.io/sharedutilities_qa:latest
replicas: 1
sslcert: perseusedgesslcert
limitcpu: 800m
limitmemory: 000Mi
requestscpu: 600m
requestsmemory: 800Mi
autoscaling:
  enabled: true