host: testsharedutilitiesservice.perseusedge.com
namespace: test
secretname: sharedutilities-dev-secret-appsettings
aspnetcore: Development
replicas: 1
sharedutilitiesrepo: primeroedgedevacr.azurecr.io/sharedutilities-dev:latest