host: previewsharedutilitiesservice.perseusedge.com
namespace: preview
secretname: sharedutilities-preview-secret-appsettings
aspnetcore: Preview
secretSPName: perseus-secret-sp-preview
secretProviderClass: aks-secret-nf-preview
#sharedutilitiesrepo: PerseusNonProdACR.azurecr.io/sharedutilities_usdaqa:latest
replicas: 1
sslcert: perseusedgesslcert
limitcpu: 500m
limitmemory: 800Mi
requestscpu: 400m
requestsmemory: 600Mi
autoscaling:
  enabled: false