host: devsharedutilitiesservice.perseusedge.com
namespace: dev
secretname: sharedutilities-dev-secret-appsettings
aspnetcore: Development
##sharedutilitiesrepo: PerseusNonProdACR.azurecr.io/sharedutilities-dev:latest
replicas: 1
sslcert: perseusedgesslcert
