apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: sharedutilities 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sharedutilities 
    spec:
      containers:
        - name: sharedutilities 
          image: primeroedgedevacr.azurecr.io/sharedutilities
          ports:
          - containerPort: a