apiVersion : apps/v1
kind: Deployment
metadata:
  name: sharedutilitiesservice-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sharedutilitiesservice
	  version: v1.0.0
  template:
    metadata:
      labels:
        app: sharedutilitiesservice
        version: v1.0.0		
      annotations:
        timestamp: "{{ date "20060102150405" .Release.Time }}"
    spec: 
      securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          fsGroup: 1001
      containers:
        - name: sharedutilitiesservice 
          image: __imageName__
          imagePullPolicy: Always
          securityContext:
            capabilities:
              drop:
               - ALL
          ports:
          - containerPort: 5000
          resources:
            limits:
              cpu: {{ .Values.limitcpu }}
              memory: {{ .Values.limitmemory }}
            requests:
              cpu: {{ .Values.requestscpu }}
              memory: {{ .Values.requestsmemory }}
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: {{ .Values.namespace }}
		      - name: VERSION
            value: v1.0.0
		      livenessProbe:
            httpGet:
              path: /live
              port: probe
                  initialDelaySeconds: 5
                  periodSeconds: 5
                readinessProbe:
                  httpGet:
                    path: /ready
                    port: probe
                  periodSeconds: 5	
      volumes:
        - name: secrets
          secret:
            secretName: {{ .Values.secretname }}     
