apiVersion : apps/v2
kind: Deployment
metadata:
  name: sharedutilitiesv2
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: sharedutilities
      version: "v2"
      track: canary
  template:
    metadata:
      labels:
        app: sharedutilities
        version: "v2"
        track: canary
      annotations:
        timestamp: "{{ date "20060102150405" .Release.Time }}"
    spec: 
      securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          fsGroup: 1001
      containers:
        - name: sharedutilities 
          image: perseusnonprodacr.azurecr.io/sharedutilities-dev:44281
          imagePullPolicy: Always
          securityContext:
            capabilities:
              drop:
               - ALL
          ports:
          - containerPort: 5000
          resources:
            limits:
              cpu: {{ .Values.limitcpu }}
              memory: {{ .Values.limitmemory }}
            requests:
              cpu: {{ .Values.requestscpu }}
              memory: {{ .Values.requestsmemory }}
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: {{ .Values.aspnetcore }}
          - name: "AppEnv"
            value: {{ .Values.namespace }}
      volumes:
        - name: secrets
          secret:
            secretName: {{ .Values.secretname }}
