apiVersion: apps/v2
kind: Deployment
metadata:
  name: sharedutilitiesservice-v1
  labels:
    app: sharedutilitiesservice
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sharedutilitiesservice
      version: v1.0.0
  template:
    metadata:
      labels:
        app: sharedutilitiesservice
        version: v1.0.0
    spec:
      containers:
      - name: sharedutilitiesservice
        image: __imageName__
        ports:
        - name: http
          containerPort: 8080
        - name: probe
          containerPort: 8086
        env:
        - name: VERSION
          value: v1.0.0
        livenessProbe:
          httpGet:
            path: /live
            port: probe
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: probe
          periodSeconds: 5