apiVersion : apps/v1
kind: Deployment
metadata:
  name: sharedutilities
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: sharedutilities
  template:
    metadata:
      labels:
        app: sharedutilities 
      annotations:
        timestamp: "{{ date "20060102150405" .Release.Time }}"
    spec: 
      securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          fsGroup: 1001
      containers:
        - name: sharedutilities 
          image: __imageName__
          imagePullPolicy: Always
          securityContext:
            capabilities:
              drop:
               - ALL
          ports:
          - containerPort: 5000
          resources:
            limits:
              cpu: 8m
              memory: 400Mi
            requests:
              cpu: 5m
              memory: 300Mi
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: {{ .Values.aspnetcore }}
          - name: "AppEnv"
            value: {{ .Values.namespace }}
          volumeMounts:
          - name: secrets
            mountPath: /app/secrets
            readOnly: true
      volumes:
        - name: secrets
          secret:
            secretName: {{ .Values.secretname }}
