apiVersion : apps/v1
kind: Deployment
metadata:
  name: sharedutilities
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sharedutilities
  template:
    metadata:
      labels:
        app: sharedutilities 
      annotations:
        timestamp: "{{ date "20060102150405" .Release.Time }}"
    spec:     
      containers:
        - name: sharedutilities 
          env:          
          - name: "image"
            valueFrom:
              secretKeyRef:
                key:  imageName
                name: {{ .Release.Name }}-auth
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: {{ .Values.aspnetcore }}
          - name: "AppEnv"
            value: {{ .Values.namespace }}
          volumeMounts:
          - name: secrets
            mountPath: /app/secrets
            readOnly: true
      volumes:
        - name: secrets
          secret:
            secretName: {{ .Values.secretname }}
