apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sharedutilities
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - host: dev.sharedutilitiesservice.gateway.perseusedge.com
      http:
        paths:
          - path: /
            backend:
              serviceName: sharedutilitiesservice
              servicePort: 80