apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sharedutilitiesv1
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: {{ .Values.sslcert }}
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: sharedutilitiesservice 
              servicePort: 80