apiVersion: v1
kind: Service
metadata:
  name: sharedutilitiesservicev1
  labels:
    app: sharedutilitiesservicev1
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 5000
  selector:
    app: sharedutilitiesservicev1