apiVersion: v1
kind: Service
metadata:
  name: sharedutilitiesservicev2
  labels:
    app: sharedutilitiesservicev2
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 5000
  selector:
    app: sharedutilitiesservicev2