apiVersion: v1
kind: Service
metadata:
  name: sharedutilitiesservice
  labels:
    app: sharedutilitiesservice
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 5000
  selector:
    app: sharedutilitiesservice
    version: 2.0.0